  [1m[35m (31.2ms)[0m  [1m[35mCREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)[0m
  [1m[35m (13.7ms)[0m  [1m[35mCREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT pg_try_advisory_lock(4514104601314011795)[0m
  [1m[35m (1.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.0ms)[0m  [1m[34mSELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"[0m  [["key", "environment"], ["value", "development"], ["created_at", "2020-02-20 01:30:32.861662"], ["updated_at", "2020-02-20 01:30:32.861662"]]
  [1m[35m (0.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.0ms)[0m  [1m[34mSELECT pg_advisory_unlock(4514104601314011795)[0m
  [1m[35m (0.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT VERSION()[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT pg_try_advisory_lock(4514104601314011795)[0m
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to DeviseTokenAuthCreateUsers (20200220013847)
  [1m[35m (1.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (31.2ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "provider" character varying DEFAULT 'email' NOT NULL, "uid" character varying DEFAULT '' NOT NULL, "encrypted_password" character varying DEFAULT '' NOT NULL, "reset_password_token" character varying, "reset_password_sent_at" timestamp, "allow_password_change" boolean DEFAULT 'f', "remember_created_at" timestamp, "confirmation_token" character varying, "confirmed_at" timestamp, "confirmation_sent_at" timestamp, "unconfirmed_email" character varying, "name" character varying, "nickname" character varying, "image" character varying, "email" character varying, "tokens" json, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL)[0m
  [1m[35m (3.9ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_email" ON "users"  ("email")[0m
  [1m[35m (4.9ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_uid_and_provider" ON "users"  ("uid", "provider")[0m
  [1m[35m (4.9ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_reset_password_token" ON "users"  ("reset_password_token")[0m
  [1m[35m (4.9ms)[0m  [1m[35mCREATE UNIQUE INDEX  "index_users_on_confirmation_token" ON "users"  ("confirmation_token")[0m
  [1m[35mSQL (1.0ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200220013847"]]
  [1m[35m (1.9ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (2.0ms)[0m  [1m[34mSELECT  "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.0ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT pg_advisory_unlock(4514104601314011795)[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Started OPTIONS "/api/users/sessions" for ::1 at 2020-02-19 22:36:52 -0400
  [1m[35m (1.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/api/users/sessions"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/api/users/sessions" for ::1 at 2020-02-19 22:39:09 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/api/users/sessions"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/api/auth/sign_up" for ::1 at 2020-02-19 22:50:09 -0400
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/api/auth/sign_up"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth/sign_up" for ::1 at 2020-02-19 22:51:09 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth/sign_up"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/users" for ::1 at 2020-02-19 22:52:06 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/users"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/users" for ::1 at 2020-02-19 22:52:22 -0400
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/users"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth/sign_up" for ::1 at 2020-02-19 22:54:06 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth/sign_up"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth/sign_up" for ::1 at 2020-02-19 22:55:49 -0400
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth/sign_up"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/auth/sign_up" for ::1 at 2020-02-19 23:01:31 -0400
  
AbstractController::ActionNotFound (The action 'new' could not be found for DeviseTokenAuth::RegistrationsController):
  
vendor/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:119:in `process'
vendor/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
vendor/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:556:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/favicon.ico" for ::1 at 2020-02-19 23:01:32 -0400
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/auth/sign_up/" for ::1 at 2020-02-19 23:01:55 -0400
  
AbstractController::ActionNotFound (The action 'new' could not be found for DeviseTokenAuth::RegistrationsController):
  
vendor/bundle/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:119:in `process'
vendor/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/mapper.rb:46:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
vendor/bundle/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/conditional_get.rb:27:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
vendor/bundle/gems/activerecord-5.1.7/lib/active_record/migration.rb:556:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth" for ::1 at 2020-02-19 23:04:11 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/sessions/auth" for ::1 at 2020-02-19 23:07:03 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/sessions/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/sessions/auth" for ::1 at 2020-02-19 23:07:11 -0400
  [1m[35m (2.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/sessions/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth" for ::1 at 2020-02-19 23:13:50 -0400
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/auth" for ::1 at 2020-02-19 23:14:11 -0400
  [1m[35m (1.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started OPTIONS "/auth" for ::1 at 2020-02-19 23:17:57 -0400
  [1m[35m (1.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [OPTIONS] "/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Started GET "/auth" for ::1 at 2020-02-19 23:18:01 -0400
  
ActionController::RoutingError (No route matches [GET] "/auth"):
  
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:63:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `block in call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `block in tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:26:in `tagged'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/tagged_logging.rb:69:in `tagged'
vendor/bundle/gems/railties-5.1.7/lib/rails/rack/logger.rb:24:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/runtime.rb:22:in `call'
vendor/bundle/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
vendor/bundle/gems/actionpack-5.1.7/lib/action_dispatch/middleware/static.rb:125:in `call'
vendor/bundle/gems/rack-2.2.2/lib/rack/sendfile.rb:110:in `call'
vendor/bundle/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/configuration.rb:227:in `call'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:674:in `handle_request'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:476:in `process_client'
vendor/bundle/gems/puma-3.12.2/lib/puma/server.rb:334:in `block in run'
vendor/bundle/gems/puma-3.12.2/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
